server:
  port: "3000"
  host: "localhost"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 300
  shutdown_timeout: 10

app:
  name: "go-htmx"
  version: "1.0.0"
  environment: "development"
  log_level: "debug"
  static_dir: "internal/static"
  template_dir: "internal/template"

security:
  trusted_proxies: ["127.0.0.1", "::1"]
  rate_limit_rpm: 1000 