version: '3.8'

networks:
  traefik:
    external: false

services:
  traefik:
    image: traefik:v3.0-alpine
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/data:/data
    networks:
      - traefik
    # Resource limits for small VPS
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '0.5'
        reservations:
          memory: 80M
          cpus: '0.2'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$2y$$10$$z7UdGJzEJkjQD7H.xO7eje8wrODYLWyOmF8Z8Cg5nHWMzW8XqmM.e"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOHTMX_APP_ENVIRONMENT=production
      - GOHTMX_SERVER_HOST=0.0.0.0
      - GOHTMX_SERVER_PORT=8080
      # Go runtime optimizations
      - GOGC=100
      - GOMEMLIMIT=200MiB
    volumes:
      - ./config.yaml:/config.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=10M
    networks:
      - traefik
    # Resource limits for small VPS
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: '0.8'
        reservations:
          memory: 100M
          cpus: '0.3'
    labels:
      - "traefik.enable=true"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.app-insecure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.app-insecure.entrypoints=web"
      - "traefik.http.routers.app-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      # HTTPS router
      - "traefik.http.routers.app.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app.middlewares=secure-headers,rate-limit"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      # Security headers for HTTPS
      - "traefik.http.middlewares.secure-headers.headers.framedeny=true"
      - "traefik.http.middlewares.secure-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.browserxssfilter=true"
      - "traefik.http.middlewares.secure-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.secure-headers.headers.stspreload=true"
      - "traefik.http.middlewares.secure-headers.headers.stsseconds=31536000"
      - "traefik.http.middlewares.secure-headers.headers.referrerpolicy=strict-origin-when-cross-origin"
      # Rate limiting
      - "traefik.http.middlewares.rate-limit.ratelimit.average=100"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=50"

  # Development version
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - GOHTMX_APP_ENVIRONMENT=development
      - GOHTMX_SERVER_HOST=0.0.0.0
      - GOHTMX_SERVER_PORT=3000
    volumes:
      - .:/app
      - ./config.dev.yaml:/app/config.yaml:ro
    profiles:
      - dev
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-dev.entrypoints=web"
      - "traefik.http.routers.app-dev.rule=Host(`dev.localhost`)"
      - "traefik.http.services.app-dev.loadbalancer.server.port=3000"
      - "traefik.http.routers.app-dev.middlewares=dev-headers"
      # Development headers (less restrictive)
      - "traefik.http.middlewares.dev-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.dev-headers.headers.accesscontrolalloworiginlist=http://localhost,http://dev.localhost"
      - "traefik.http.middlewares.dev-headers.headers.customrequestheaders.X-Forwarded-Proto=http" 