version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOHTMX_APP_ENVIRONMENT=production
      - GOHTMX_SERVER_HOST=0.0.0.0
      - GOHTMX_SERVER_PORT=8080
    volumes:
      - ./config.yaml:/config.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

  # Development version
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - GOHTMX_APP_ENVIRONMENT=development
      - GOHTMX_SERVER_HOST=0.0.0.0
      - GOHTMX_SERVER_PORT=3000
    volumes:
      - .:/app
      - ./config.dev.yaml:/app/config.yaml:ro
    profiles:
      - dev
    restart: unless-stopped 