# Traefik configuration with Let's Encrypt HTTP challenge (no API tokens needed)
api:
  dashboard: true
  debug: false

entryPoints:
  web:
    address: ":80"
    # Don't redirect here - let individual services handle it
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    pollInterval: "30s"

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com  # Change this to your email
      storage: /data/acme.json
      # HTTP challenge - works with any domain provider
      httpChallenge:
        entryPoint: web

# Global defaults - optimized for small VPS
global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: 10

log:
  level: INFO

# Access logging
accessLog:
  filePath: "/data/access.log"
  bufferingSize: 50
  filters:
    statusCodes: ["400-599"]  # Only log errors
    minDuration: "1s"

# Connection timeouts for small VPS
entryPoints:
  web:
    transport:
      lifeCycle:
        graceTimeOut: "10s"
      respondingTimeouts:
        readTimeout: "30s"
        writeTimeout: "30s"
        idleTimeout: "60s"
  websecure:
    transport:
      lifeCycle:
        graceTimeOut: "10s"
      respondingTimeouts:
        readTimeout: "30s"
        writeTimeout: "30s"
        idleTimeout: "60s" 